#!/bin/bash

function has_yum {
  [[ -n "$(command -v yum)" ]]
}

function has_apt_get {
  [[ -n "$(command -v apt-get)" ]]
}

function has_brew {
  [[ "$OSTYPE" == "darwin"* ]]
}

function run_it {
  local host_type="$1"

  if [[ "$host_type" == "vagrant" ]]; then
    if $(has_apt_get); then
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y jq virtualbox vagrant awscli openssh-server
    elif $(has_yum); then
        sudo yum install -y jq virtualbox vagrant awscli openssh-server
    elif $(has_brew); then
        sudo brew install -y jq virtualbox vagrant awscli
    else
        echo "Could not find apt-get, yum, or brew. Cannot install dependencies on this OS."
        exit 1
    fi
  else
    if $(has_apt_get); then
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y jq awscli openssh-server
    elif $(has_yum); then
        sudo yum install -y jq awscli openssh-server
    elif $(has_brew); then
        sudo brew install -y jq awscli
    else
        echo "Could not find apt-get, yum, or brew. Cannot install dependencies on this OS."
        exit 1
    fi
  fi

}

function install {
  local resourcetier="$TF_VAR_resourcetier"
  local configure_aws="false"
  local host_type="vagrant"
  
  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --host-type)
        host_type="$2"
        shift
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  run_it "$host_type"
}

install "$@"