#!/bin/bash

function has_yum {
  [[ -n "$(command -v yum)" ]]
}

function has_apt_get {
  [[ -n "$(command -v apt-get)" ]]
}

function has_brew {
  [[ "$OSTYPE" == "darwin"* ]]
}

if $(has_apt_get); then
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y jq virtualbox vagrant awscli openssh-server
elif $(has_yum); then
    sudo yum install -y jq virtualbox vagrant awscli openssh-server
elif $(has_brew); then
    sudo brew install -y jq virtualbox vagrant awscli
else
    echo "Could not find apt-get, yum, or brew. Cannot install dependencies on this OS."
    exit 1
fi