#!/bin/bash
set -e

exit_if_error() {
  local exit_code=$1
  shift
  [[ $exit_code ]] &&               # do nothing if no error code passed
    ((exit_code != 0)) && {         # do nothing if error code is 0
      printf 'ERROR: %s\n' "$@" >&2 # we can use better logging here
      exit "$exit_code"             # we could also check to make sure
                                    # error code is numeric when passed
    }
}

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

# Raise error if var isn't defined.
if [[ -z "$AWS_DEFAULT_REGION" ]]; then
    exit_if_error 1 "AWS_DEFAULT_REGION not defined.  Ensure you have run 'source update_vars.sh' from the repository root folder."
fi
if [[ -z "$TF_VAR_bucket_extension" ]]; then
    exit_if_error 1 "TF_VAR_bucket_extension not defined.  Ensure you have run 'source update_vars.sh' from the repository root folder."
fi

manifest="$SCRIPTDIR/modules/openvpn-server-ami/manifest.json"
if [[ -f "$manifest" ]]; then
    export TF_VAR_openvpn_server_ami="$(jq -r '.builds[] | select(.name == "openvpn-server-ami") | .artifact_id' "$manifest" | tail -1 | cut -d ":" -f2)"
    echo "Found openvpn_server_ami in manifest: TF_VAR_openvpn_server_ami=$TF_VAR_openvpn_server_ami"
else
    echo "Manifest for ami does not exist.  Build the base ami and try again."
    exit 1
fi

# AMI query by commit
ami_role="firehawk_openvpn_server_ami"
export TF_VAR_ami_commit_hash="$(cd $TF_VAR_firehawk_path/../packer-firehawk-amis/modules/firehawk-ami; git rev-parse HEAD)"
echo "Query AMI for Vault server with commit: $TF_VAR_ami_commit_hash"
query=$(aws ec2 describe-images --filters "Name=tag:ami_role,Values=$firehawk_centos7_ami" --filters "Name=tag:commit_hash,Values=$TF_VAR_ami_commit_hash" --owners self --region $AWS_DEFAULT_REGION --query 'sort_by(Images, &CreationDate)[].ImageId' --output json | jq '.[0]' --raw-output)
if [[ "$query" != "null" ]]; then
    export TF_VAR_openvpn_server_ami="$query"
    echo "Found openvpn_server_ami with tag matching commit: TF_VAR_openvpn_server_ami=$TF_VAR_openvpn_server_ami"
fi
if [[ -z "$TF_VAR_openvpn_server_ami" ]]; then
  exit_if_error 1 "Images required for deployment are not present.  You will need to build them before continuing."
fi

# If sourced, dont execute
(return 0 2>/dev/null) && sourced=1 || sourced=0
echo "Script sourced: $sourced"
if [[ "$sourced" -eq 0 ]]; then
    terraform init \
        -input=false \
        -backend-config="bucket=state.terraform.$TF_VAR_bucket_extension" \
        -backend-config="key=$TF_VAR_resourcetier/terraform-aws-vpn/terraform.tfstate" \
        -backend-config="region=$AWS_DEFAULT_REGION" \
        -backend-config="dynamodb_table=locks.state.terraform.$TF_VAR_bucket_extension"
    terraform plan -out=tfplan -input=false
fi

set +e