#!/bin/bash

# Configure SSH from an AWS access key using an SQS queue with Vault.

set -e

EXECDIR="$(pwd)"
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" # The directory of this script

set -x

function print_usage {
  echo
  echo "Usage: init-aws-auth [OPTIONS]"
  echo
  echo "Signs a public key with Vault for use as an SSH client, generating a public certificate in the same directory as the public key with the suffix '-cert.pub'."
  echo "A cloud host must be running sign_ssh_key to poll for the result."
  echo
  echo "Options:"
  echo
  echo -e "  --resourcetier\tThe environment to use (dev/blue/green/main)"
  echo
  echo "Example: Sign this hosts public key with Vault in a dev environment."
  echo
  echo "  init-aws-auth --resourcetier dev"
}

function log {
  local -r level="$1"
  local -r message="$2"
  local -r timestamp=$(date +"%Y-%m-%d %H:%M:%S")
  >&2 echo -e "${timestamp} [${level}] [$SCRIPT_NAME] ${message}"
}

function log_info {
  local -r message="$1"
  log "INFO" "$message"
}

function log_warn {
  local -r message="$1"
  log "WARN" "$message"
}

function log_error {
  local -r message="$1"
  log "ERROR" "$message"
}

function error_if_empty {
  if [[ -z "$2" ]]; then
    log_error "$1"
    exit 1
  fi
  return
}

function assert_not_empty {
  local -r arg_name="$1"
  local -r arg_value="$2"

  if [[ -z "$arg_value" ]]; then
    log_error "The value for '$arg_name' cannot be empty"
    print_usage
    exit 1
  fi
}

function install_packages {
  sudo apt-get install -y awscli jq
  sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python3
  sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python-apt
  sudo apt install -y python3-pip
  python3 -m pip install --upgrade pip
  python3 -m pip install boto3
  # sudo DEBIAN_FRONTEND=noninteractive apt-get install -y python-pip
  # LC_ALL=C && sudo pip install boto3
  python3 -m pip install --user --upgrade awscli
}

function keygen {
  ssh-keygen -q -b 2048 -t rsa -f $HOME/.ssh/id_rsa -C "" -N ""
}
# resourcetier=
function sign_pub_key_request {
  resourcetier="$1"
  $SCRIPTDIR/sign-ssh-key/sign_ssh_key.sh --aws-configure --resourcetier "$resourcetier"
}

function install {
  local resourcetier=""
  
  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --resourcetier)
        resourcetier="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  error_if_empty "Argument resourcetier or env var TF_VAR_resourcetier not provided" "$resourcetier"

  install_packages
  keygen
  sign_pub_key_request "$resourcetier"
}

install "$@"