---
collections:
  - name: https://github.com/firehawkvfx/ansible_collection_core.git # note that if an existing folder is present with the same name, it will be used in place of downloading the requirements file.
    type: git
    # version: 1.0.0