# configures autologin for open vpn and routes.

# to update routes only for the deployuser host, execute 
# ansible-playbook -i ansible/inventory ansible/openvpn.yaml -v --extra-vars "" --tags add-routes

- hosts: "{{ variable_host | default('firehawk_gateway') }}"
  remote_user: deployuser
  gather_facts: "{{ variable_gather_facts | default('false') }}"
  become: true

  vars:
    client_network: None
    client_netmask_bits: None

  roles:
  # - {role: 'openvpn-gateway', tags: 'init'}

  tasks:
  - name: allow ip forwarding, uncomment
    replace:
      path: /etc/sysctl.conf
      regexp: '^#(.*net.ipv4.ip_forward=1.*)'
      replace: '\1'
    tags:
    - init