---
# this takes the configuration files form the server in preaparation for htem to be used on the client.
# - name: Ensures dir exists
#   file:
#     path: "~/openvpn_config"
#     state: directory
#   delegate_to: localhost
#   # become_user: deployuser
#   remote_user: deployuser
#   become: yes

- name: allow ip forwarding, uncomment line
  replace:
    path: /etc/sysctl.conf
    regexp: '^#(.*net.ipv4.ip_forward=1.*)'
    replace: '\1'
  # become_user: openvpnas
  become: yes

- name: contents of /usr/local/openvpn_as/scripts/seperate/
  command: "ls /usr/local/openvpn_as/scripts/seperate/"
  become_user: openvpnas
  become: yes
  register: openvpn_contents

- debug:
    var: openvpn_contents.stdout

- name: prep permissions
  file:
    path: /usr/local/openvpn_as/scripts/seperate/{{ item }}
    mode: '0400'
  with_items:
    - ca.crt
    - client.crt
    - client.key
    - ta.key
    - client.ovpn # becomes ~/openvpn_config/openvpn.conf

# - name: Ansible copy file force
#   fetch:
#     src: /usr/local/openvpn_as/scripts/seperate/{{ item }}
#     dest: ~/openvpn_config/
#     force: yes
#     flat: true
#     mode: '0400'
#   with_items:
#     - ca.crt
#     - client.crt
#     - client.key
#     - ta.key

# - name: Ansible copy client.ovpn to openvpn.conf
#   fetch:
#     src: /usr/local/openvpn_as/scripts/seperate/client.ovpn
#     dest: ~/openvpn_config/openvpn.conf
#     force: yes
#     flat: true
#     mode: '0400'

- name: inherit changes made to /etc/sysctl.conf
  command: 'sysctl -p'
  become_user: openvpnas
  become: yes


### copy back to gateway next role
